name: todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^20.0.0
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  riverpod: ^3.2.1
  supabase_flutter: ^2.12.0
  timezone: ^0.10.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
